In [1]:
pip install nnfs

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [4]:
class Layer_Dense:
    def __init__(self,n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons)) 
    def forward(self , inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

In [5]:
class Activation_ReLU:
    def forward (self, inputs):
        self.output = np. maximum(0, inputs)

In [6]:
class Activation_Softmax:
    def forward (self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values , axis=1, keepdims=True)
        self.output = probabilities

In [7]:
X, y = spiral_data(samples = 100 , classes = 3)

In [8]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

In [9]:
dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

In [10]:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.33331832 0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [11]:
class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [14]:
class Loss_CategoricalCrossentropy(Loss):
    def forward (self, y_pred, y_true):
        samples = len (y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        
        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples), y_true]
        
        elif len(y_true.shape) == 2:
            correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)
        
        negative_log_likelihoods = -np.log (correct_confidences)
        return negative_log_likelihoods

In [15]:
loss_function = Loss_CategoricalCrossentropy()
loss= loss_function.calculate (activation2.output, y) 

print("Loss:", loss)

Loss: 1.098445
